#!/bin/bash
set -euo pipefail

# Usage: ./scripts/load-generator.sh <app-url>
# Generates continuous traffic to the journal app to trigger alerts faster

if [ $# -lt 1 ]; then
  echo "Usage: $0 <app-url>"
  echo "Example: $0 http://20.53.1.100"
  exit 1
fi

APP_URL="$1"
INTERVAL="${2:-0.5}"
USER_ID="load-test-user"

echo "=== Load Generator ==="
echo "Target: $APP_URL"
echo "Press Ctrl+C to stop"
echo ""

# Create a test journal entry first
echo "Creating test entry..."
curl -s -X POST "${APP_URL}/api/journals/${USER_ID}" \
  -H "Content-Type: application/json" \
  -d '{"title":"Load Test Entry","content":"Generated by load test","mood":"neutral","tags":["test"]}' | head -1
echo ""

COUNTER=0
while true; do
  COUNTER=$((COUNTER + 1))

  # Mix of different request types
  case $((COUNTER % 5)) in
    0) curl -s -o /dev/null -w "%{http_code}" "${APP_URL}/health" ;;
    1) curl -s -o /dev/null -w "%{http_code}" "${APP_URL}/ready" ;;
    2) curl -s -o /dev/null -w "%{http_code}" "${APP_URL}/api/journals/${USER_ID}" ;;
    3) curl -s -o /dev/null -w "%{http_code}" "${APP_URL}/metrics" ;;
    4) curl -s -o /dev/null -w "%{http_code}" -X POST "${APP_URL}/api/journals/${USER_ID}" \
         -H "Content-Type: application/json" \
         -d "{\"title\":\"Entry ${COUNTER}\",\"content\":\"Load test entry ${COUNTER}\",\"mood\":\"neutral\"}" ;;
  esac

  printf "\r[%d] Requests sent..." "$COUNTER"
  sleep "$INTERVAL"
done
